name: data_platform_prd

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prd
      args:
        UV_VERSION: latest
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    dns:
      - 8.8.8.8 # Google Public DNS Primary
      - 1.1.1.1 # Cloudflare DNS Primary
    depends_on:
      - rustfs
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      target: dashboard
      args:
        UV_VERSION: latest
    ports:
      - "8501:8501"
    env_file:
      - ./.env
    depends_on:
      - rustfs
    restart: unless-stopped
  rustfs:
    image: rustfs/rustfs:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - rustfs-data:/data
    env_file:
      - ./.env
    environment:
      - RUSTFS_CONSOLE_ENABLE=true
    command: >
      --address :9000
      --console-enable
      /data
    restart: always

volumes:
  rustfs-data:
