catalog:
  dlh_dev:
    type: sql
    uri: sqlite:////workspace/configuration/iceberg/catalog/dlh_dev.db
    warehouse: s3://jp-power-grid-dev
    s3.endpoint: http://rustfs:9000
    s3.region: us-east-1
    s3.path-style-access: "true"
